version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pos_postgres
    restart: always
    environment:
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_password
      POSTGRES_DB: restaurant_pos
    ports:
      - "5432:5432"
    volumes:
      - pos_db_data:/var/lib/postgresql/data

volumes:
  pos_db_data:
