using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace RestaurantPOS.api.src.Infrastructure.Persistence.Migrations;
public partial class AddPayroll : Migration
{
    protected override void Up(MigrationBuilder m)
    {
        m.AddColumn<string>("EmployeeType", "Employees", type: "text", nullable: false, defaultValue: "FullTime");
        m.Sql("CREATE TABLE IF NOT EXISTS \"EmployeeSalaryProfiles\" (\"Id\" uuid NOT NULL PRIMARY KEY, \"EmployeeId\" uuid NOT NULL, \"BranchId\" uuid NOT NULL, \"EmployeeType\" text NOT NULL, \"MonthlySalary\" numeric NOT NULL, \"HourlyRate\" numeric NOT NULL, \"StandardWorkDays\" numeric NOT NULL, \"StandardWorkHours\" numeric NOT NULL, \"OvertimeRate\" numeric NOT NULL, \"Allowance\" numeric NOT NULL, \"EffectiveFrom\" timestamptz NOT NULL, \"EffectiveTo\" timestamptz NULL, \"CreatedAt\" timestamptz NOT NULL, \"UpdatedAt\" timestamptz NOT NULL);");
        m.Sql("CREATE TABLE IF NOT EXISTS \"PayrollSettings\" (\"Id\" uuid NOT NULL PRIMARY KEY, \"BranchId\" uuid NULL, \"StandardWorkDays\" numeric NOT NULL, \"StandardWorkHoursPerDay\" numeric NOT NULL, \"FullTimeDeductionPerMissingDay\" numeric NOT NULL, \"DefaultPartTimeHourlyRate\" numeric NOT NULL, \"OvertimeEnabled\" boolean NOT NULL, \"OvertimeMultiplier\" numeric NOT NULL, \"UpdatedAt\" timestamptz NOT NULL);");
        m.Sql("CREATE TABLE IF NOT EXISTS \"Payrolls\" (\"Id\" uuid NOT NULL PRIMARY KEY, \"EmployeeId\" uuid NOT NULL, \"BranchId\" uuid NOT NULL, \"Month\" integer NOT NULL, \"Year\" integer NOT NULL, \"EmployeeType\" text NOT NULL, \"StandardWorkDays\" numeric NOT NULL, \"ActualWorkDays\" numeric NOT NULL, \"TotalHours\" numeric NOT NULL, \"RegularHours\" numeric NOT NULL, \"OvertimeHours\" numeric NOT NULL, \"BaseSalary\" numeric NOT NULL, \"HourlyRate\" numeric NOT NULL, \"RegularPay\" numeric NOT NULL, \"OvertimePay\" numeric NOT NULL, \"Allowance\" numeric NOT NULL, \"Bonus\" numeric NOT NULL, \"Deduction\" numeric NOT NULL, \"GrossSalary\" numeric NOT NULL, \"NetSalary\" numeric NOT NULL, \"Status\" text NOT NULL, \"CalculatedAt\" timestamptz NULL, \"LockedAt\" timestamptz NULL, \"PaidAt\" timestamptz NULL, \"CreatedAt\" timestamptz NOT NULL, \"UpdatedAt\" timestamptz NOT NULL);");
        m.Sql("CREATE TABLE IF NOT EXISTS \"PayrollAdjustments\" (\"Id\" uuid NOT NULL PRIMARY KEY, \"PayrollId\" uuid NOT NULL, \"Type\" text NOT NULL, \"Amount\" numeric NOT NULL, \"Reason\" text NOT NULL, \"CreatedBy\" uuid NULL, \"CreatedAt\" timestamptz NOT NULL);");
        m.Sql("CREATE INDEX IF NOT EXISTS \"IX_EmployeeSalaryProfiles_EmployeeId_BranchId_EffectiveFrom\" ON \"EmployeeSalaryProfiles\" (\"EmployeeId\", \"BranchId\", \"EffectiveFrom\"); CREATE UNIQUE INDEX IF NOT EXISTS \"IX_PayrollSettings_BranchId\" ON \"PayrollSettings\" (\"BranchId\"); CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Payrolls_EmployeeId_BranchId_Month_Year\" ON \"Payrolls\" (\"EmployeeId\", \"BranchId\", \"Month\", \"Year\"); CREATE INDEX IF NOT EXISTS \"IX_PayrollAdjustments_PayrollId_CreatedAt\" ON \"PayrollAdjustments\" (\"PayrollId\", \"CreatedAt\");");
    }
    protected override void Down(MigrationBuilder m) { m.Sql("DROP TABLE IF EXISTS \"PayrollAdjustments\"; DROP TABLE IF EXISTS \"Payrolls\"; DROP TABLE IF EXISTS \"PayrollSettings\"; DROP TABLE IF EXISTS \"EmployeeSalaryProfiles\";"); m.DropColumn("EmployeeType", "Employees"); }
}
