import React, { useEffect, useMemo, useState } from 'react';
import { Calculator, Lock, Unlock, Plus, X } from 'lucide-react';
import { API_URL } from '../../../config';

type Branch = { id: string; name: string };
type Employee = { id: string; fullName: string; branchId?: string; employeeType?: string; basicSalary?: number };
type Payroll = { id: string; employeeId: string; employeeName?: string; branchId: string; employeeType: string; actualWorkDays: number; standardWorkDays: number; totalHours: number; overtimeHours: number; regularPay: number; overtimePay: number; allowance: number; bonus: number; deduction: number; netSalary: number; status: string };
const money = (n = 0) => `${Math.round(n).toLocaleString('vi-VN')}đ`;
const auth = () => ({ 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('token') || ''}` });

export default function PayrollPage() {
  const now = new Date(); const [month, setMonth] = useState(now.getMonth() + 1); const [year, setYear] = useState(now.getFullYear());
  const [branches, setBranches] = useState<Branch[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [branchId, setBranchId] = useState(localStorage.getItem('selectedBranchId') || ''); const [rows, setRows] = useState<Payroll[]>([]); const [loading, setLoading] = useState(false); const [selected, setSelected] = useState<any>(null); const [adjust, setAdjust] = useState({ type: 'Bonus', amount: '', reason: '' }); const [salary, setSalary] = useState({ employeeId: '', employeeType: 'FullTime', monthlySalary: '', hourlyRate: '', allowance: '', effectiveFrom: `${year}-${String(month).padStart(2, '0')}-01` }); const [rules, setRules] = useState({ standardWorkDays: 26, standardWorkHoursPerDay: 8, fullTimeDeductionPerMissingDay: 0, defaultPartTimeHourlyRate: 0, overtimeEnabled: true, overtimeMultiplier: 1.5 });
  const branchName = useMemo(() => branches.find(b => b.id === branchId)?.name || 'Tất cả cơ sở', [branches, branchId]);
  const load = async () => { setLoading(true); try { const [r, e, b, s] = await Promise.all([fetch(`${API_URL}/api/Payroll?month=${month}&year=${year}${branchId ? `&branchId=${branchId}` : ''}`, { headers: auth() }), fetch(`${API_URL}/api/Employee?isActive=true`, { headers: auth() }), fetch(`${API_URL}/api/Branch`, { headers: auth() }), fetch(`${API_URL}/api/Payroll/settings${branchId ? `?branchId=${branchId}` : ''}`, { headers: auth() })]); const rd = await r.json(); setRows(rd.items || []); setEmployees(await e.json()); setBranches(await b.json()); if (s.ok) setRules(await s.json()); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [month, year, branchId]);
  const calculate = async (employee: Employee) => { const bid = employee.branchId || branchId; if (!bid) return alert('Nhân viên chưa được gán cơ sở.'); const r = await fetch(`${API_URL}/api/Payroll/calculate`, { method: 'POST', headers: auth(), body: JSON.stringify({ employeeId: employee.id, branchId: bid, month, year, overtimeHours: null }) }); if (!r.ok) return alert((await r.json()).message || 'Không thể tính lương'); await load(); };
  const calculateAll = async () => { const targets = employees.filter(e => e.branchId && (!branchId || e.branchId === branchId)); if (!targets.length) return alert('Không có nhân viên đã gán cơ sở.'); for (const employee of targets) await calculate(employee); };
  const saveRules = async () => { const r = await fetch(`${API_URL}/api/Payroll/settings${branchId ? `?branchId=${branchId}` : ''}`, { method: 'PUT', headers: auth(), body: JSON.stringify(rules) }); if (!r.ok) return alert((await r.json()).message || 'Không lưu được quy tắc'); alert('Đã lưu quy tắc tính lương'); };
  const changeStatus = async (id: string, action: 'lock' | 'unlock') => { const r = await fetch(`${API_URL}/api/Payroll/${id}/${action}`, { method: 'POST', headers: auth() }); if (!r.ok) alert((await r.json()).message || 'Không thể cập nhật trạng thái'); else { setSelected(null); await load(); } };
  const openDetail = async (row: Payroll) => { const r = await fetch(`${API_URL}/api/Payroll/${row.id}`, { headers: auth() }); setSelected(await r.json()); };
  const addAdjustment = async () => { if (!selected) return; const r = await fetch(`${API_URL}/api/Payroll/${selected.p.id}/adjustments`, { method: 'POST', headers: auth(), body: JSON.stringify({ type: adjust.type, amount: Number(adjust.amount), reason: adjust.reason }) }); if (!r.ok) return alert((await r.json()).message || 'Khoản điều chỉnh không hợp lệ'); setAdjust({ type: 'Bonus', amount: '', reason: '' }); await load(); await openDetail(rows.find(x => x.id === selected.p.id) || selected.p); };
  const saveSalary = async () => { const e = employees.find(x => x.id === salary.employeeId); const bid = e?.branchId || branchId; if (!e || !bid) return alert('Chọn nhân viên có cơ sở.'); const r = await fetch(`${API_URL}/api/Payroll/employees/${e.id}/salary?branchId=${bid}`, { method: 'PUT', headers: auth(), body: JSON.stringify({ ...salary, employeeId: e.id, branchId: bid, monthlySalary: Number(salary.monthlySalary) || 0, hourlyRate: Number(salary.hourlyRate) || 0, allowance: Number(salary.allowance) || 0, standardWorkDays: 26, standardWorkHours: 8, overtimeRate: 1.5, effectiveFrom: new Date(salary.effectiveFrom).toISOString() }) }); if (!r.ok) return alert((await r.json()).message || 'Không lưu được cấu hình lương'); alert('Đã lưu cấu hình lương'); };
  const total = rows.reduce((s, r) => s + r.netSalary, 0); const calculatedEmployees = rows.length;
  const userRole = localStorage.getItem('userRole');
  const ownBranchId = localStorage.getItem('selectedBranchId');

  return <div className="p-6 max-w-[1500px] mx-auto"><div className="flex flex-wrap items-center justify-between gap-3 mb-6"><div><h1 className="text-2xl font-black text-slate-800">Quản lý lương</h1><p className="text-sm text-slate-500">Tổng hợp từ chấm công thực tế · {branchName}</p></div><div className="flex flex-wrap gap-2"><select value={month} onChange={e => setMonth(Number(e.target.value))} className="border rounded-lg px-3 py-2">{Array.from({ length: 12 }, (_, i) => <option key={i} value={i + 1}>Tháng {i + 1}</option>)}</select><input type="number" value={year} onChange={e => setYear(Number(e.target.value))} className="border rounded-lg px-3 py-2 w-24" /><select value={branchId} onChange={e => setBranchId(e.target.value)} disabled={userRole === 'manager'} className="border rounded-lg px-3 py-2">{userRole === 'admin' && <option value="">Tất cả cơ sở</option>}{branches.filter(b => userRole === 'admin' || b.id === ownBranchId).map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select><button onClick={() => void calculateAll()} className="bg-blue-600 text-white rounded-lg px-3 py-2 font-bold">Tính lương tất cả</button></div></div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6"><div className="bg-white rounded-2xl p-5 shadow-sm"><p className="text-xs text-slate-500">Nhân viên đã tính</p><strong className="text-2xl">{calculatedEmployees}</strong></div><div className="bg-white rounded-2xl p-5 shadow-sm"><p className="text-xs text-slate-500">Tổng quỹ lương thực nhận</p><strong className="text-2xl text-blue-600">{money(total)}</strong></div><div className="bg-white rounded-2xl p-5 shadow-sm"><p className="text-xs text-slate-500">Đã chốt</p><strong className="text-2xl text-emerald-600">{rows.filter(r => r.status === 'Locked' || r.status === 'Paid').length}</strong></div></div>
    <section className="bg-white rounded-2xl shadow-sm p-5 mb-6"><h2 className="font-black mb-4">Cấu hình lương nhân viên</h2><div className="grid grid-cols-1 md:grid-cols-6 gap-2"><select className="border rounded-lg p-2" value={salary.employeeId} onChange={e => setSalary({ ...salary, employeeId: e.target.value })}><option value="">Chọn nhân viên</option>{employees.map(e => <option key={e.id} value={e.id}>{e.fullName}</option>)}</select><select className="border rounded-lg p-2" value={salary.employeeType} onChange={e => setSalary({ ...salary, employeeType: e.target.value })}><option value="FullTime">Full-time</option><option value="PartTime">Part-time</option></select><input className="border rounded-lg p-2" type="number" placeholder="Lương tháng" value={salary.monthlySalary} onChange={e => setSalary({ ...salary, monthlySalary: e.target.value })} /><input className="border rounded-lg p-2" type="number" placeholder="Đơn giá/giờ" value={salary.hourlyRate} onChange={e => setSalary({ ...salary, hourlyRate: e.target.value })} /><input className="border rounded-lg p-2" type="number" placeholder="Phụ cấp" value={salary.allowance} onChange={e => setSalary({ ...salary, allowance: e.target.value })} /><button onClick={() => void saveSalary()} className="bg-blue-600 text-white rounded-lg font-bold">Lưu cấu hình</button></div></section>
    <section className="bg-white rounded-2xl shadow-sm p-5 mb-6"><h2 className="font-black mb-4">Quy tắc tính lương {branchId ? `· ${branchName}` : 'toàn hệ thống'}</h2><div className="grid grid-cols-2 md:grid-cols-6 gap-2"><input className="border rounded-lg p-2" type="number" title="Ngày công chuẩn" value={rules.standardWorkDays} onChange={e => setRules({ ...rules, standardWorkDays: Number(e.target.value) })} /><input className="border rounded-lg p-2" type="number" title="Giờ công/ngày" value={rules.standardWorkHoursPerDay} onChange={e => setRules({ ...rules, standardWorkHoursPerDay: Number(e.target.value) })} /><input className="border rounded-lg p-2" type="number" title="Khấu trừ thiếu công/ngày" placeholder="Khấu trừ/ngày" value={rules.fullTimeDeductionPerMissingDay} onChange={e => setRules({ ...rules, fullTimeDeductionPerMissingDay: Number(e.target.value) })} /><input className="border rounded-lg p-2" type="number" title="Đơn giá mặc định part-time" placeholder="Part-time/giờ" value={rules.defaultPartTimeHourlyRate} onChange={e => setRules({ ...rules, defaultPartTimeHourlyRate: Number(e.target.value) })} /><input className="border rounded-lg p-2" type="number" step="0.1" title="Hệ số tăng ca" value={rules.overtimeMultiplier} onChange={e => setRules({ ...rules, overtimeMultiplier: Number(e.target.value) })} /><button onClick={() => void saveRules()} className="bg-slate-800 text-white rounded-lg font-bold">Lưu quy tắc</button></div></section>
    <section className="bg-white rounded-2xl shadow-sm overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-500 text-xs uppercase"><tr><th className="p-4 text-left">Nhân viên</th><th>Loại</th><th>Công/giờ</th><th>Tăng ca</th><th>Thực nhận</th><th>Trạng thái</th><th></th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className="p-8 text-center">Đang tải...</td></tr> : rows.map(r => <tr key={r.id} className="border-t"><td className="p-4 font-bold">{r.employeeName || r.employeeId}</td><td className="text-center">{r.employeeType === 'PartTime' ? 'Part-time' : 'Full-time'}</td><td className="text-center">{r.employeeType === 'PartTime' ? `${r.totalHours}h` : `${r.actualWorkDays}/${r.standardWorkDays} ngày`}</td><td className="text-center">{r.overtimeHours}h</td><td className="text-right font-black text-blue-700">{money(r.netSalary)}</td><td className="text-center"><span className={`px-2 py-1 rounded-full text-xs font-bold ${r.status === 'Locked' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{r.status === 'Locked' ? 'Đã chốt' : 'Đã tính'}</span></td><td className="p-3 text-right"><button className="text-blue-600 font-bold mr-3" onClick={() => void openDetail(r)}>Chi tiết</button><button className="text-slate-600" title="Tính lại" disabled={r.status === 'Locked'} onClick={() => void calculate(employees.find(e => e.id === r.employeeId) || { id: r.employeeId, fullName: '' })}><Calculator size={16}/></button></td></tr>)}{!loading && rows.length === 0 && <tr><td colSpan={7} className="p-10 text-center text-slate-400">Chưa có bảng lương. Hãy lưu cấu hình rồi tính lương từ danh sách nhân viên.</td></tr>}</tbody></table></section>
    {selected?.p && <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl w-full max-w-xl p-6"><div className="flex justify-between"><h2 className="text-xl font-black">Chi tiết lương · {selected.employeeName}</h2><button onClick={() => setSelected(null)}><X/></button></div><p className="text-sm text-slate-500 mb-4">{selected.branchName} · {month}/{year}</p><div className="grid grid-cols-2 gap-3 text-sm">{[['Lương cơ bản', selected.p.baseSalary], ['Ngày công', `${selected.p.actualWorkDays}/${selected.p.standardWorkDays}`], ['Tổng giờ', `${selected.p.totalHours}h`], ['Tăng ca', `${selected.p.overtimeHours}h`], ['Phụ cấp', selected.p.allowance], ['Thưởng', selected.p.bonus], ['Khấu trừ', selected.p.deduction], ['Thực nhận', selected.p.netSalary]].map(([k, v]) => <div key={String(k)} className="border rounded-lg p-3"><span className="text-slate-500">{k}</span><strong className="block mt-1">{typeof v === 'number' ? money(v) : v}</strong></div>)}</div><div className="mt-5 border-t pt-4"><h3 className="font-bold mb-2">Thêm khoản cộng/trừ</h3><div className="flex gap-2"><select className="border rounded p-2" value={adjust.type} onChange={e => setAdjust({ ...adjust, type: e.target.value })}><option value="Bonus">Thưởng</option><option value="Deduction">Khấu trừ</option><option value="Allowance">Phụ cấp</option></select><input className="border rounded p-2 w-28" type="number" placeholder="Số tiền" value={adjust.amount} onChange={e => setAdjust({ ...adjust, amount: e.target.value })}/><input className="border rounded p-2 flex-1" placeholder="Lý do" value={adjust.reason} onChange={e => setAdjust({ ...adjust, reason: e.target.value })}/><button onClick={() => void addAdjustment()} className="bg-blue-600 text-white rounded p-2"><Plus size={18}/></button></div></div><div className="flex justify-end gap-2 mt-5"><button className="border rounded-lg px-4 py-2" onClick={() => setSelected(null)}>Đóng</button>{selected.p.status === 'Locked' ? <button className="bg-amber-600 text-white rounded-lg px-4 py-2 flex gap-2" onClick={() => void changeStatus(selected.p.id, 'unlock')}><Unlock size={16}/> Mở lại</button> : <button className="bg-emerald-600 text-white rounded-lg px-4 py-2 flex gap-2" onClick={() => void changeStatus(selected.p.id, 'lock')}><Lock size={16}/> Chốt lương</button>}</div></div></div>}</div>;
}
