import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, BarChart3, CheckCircle2, ChevronDown, Clock3, CreditCard, DollarSign, LayoutDashboard, Loader2, Package, RefreshCw, ShoppingBag, TrendingUp, Users } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { API_URL } from '../../../config';

interface DashboardData {
  todayRevenue: number; revenueTrend: number; totalOrders: number; customerCount: number; totalExpenses: number; estimatedProfit: number;
  topProducts: Array<{ name: string; quantity: number; revenue: number }>;
  chartData: Array<{ time: string; amount: number }>;
  weeklyRevenue: Array<{ date: string; amount: number }>;
  monthlyRevenue: Array<{ month: string; amount: number }>;
  branchRevenue: Array<{ name: string; value: number }>;
  recentOrders: Array<{ invoiceCode: string; customerName: string; totalAmount: number; createdAt: string; tableName: string; branchName?: string; status?: string }>;
  orderStatuses?: Array<{ name: string; value: number }>;
  paymentMethods?: Array<{ name: string; value: number }>;
}
interface Branch { id: string; name: string }

const COLORS = ['#2563eb', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6'];
const currency = (value = 0) => `${new Intl.NumberFormat('vi-VN').format(value)}đ`;
const compactCurrency = (value: number) => value >= 1000000 ? `${(value / 1000000).toFixed(1)}M` : `${Math.round(value / 1000)}k`;

const EmptyState = ({ text = 'Chưa có dữ liệu trong khoảng thời gian này.' }: { text?: string }) => <div className="flex min-h-[180px] items-center justify-center rounded-2xl bg-slate-50 px-4 text-center text-sm font-medium text-slate-400">{text}</div>;
const Skeleton = ({ className = '' }: { className?: string }) => <div className={`animate-pulse rounded bg-slate-200 ${className}`} />;
const Card = ({ children, className = '' }: { children: React.ReactNode; className?: string }) => <section className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-sm ${className}`}>{children}</section>;
const SectionTitle = ({ icon: Icon, children, action }: { icon: React.ElementType; children: React.ReactNode; action?: React.ReactNode }) => <div className="mb-5 flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-base font-bold text-slate-800"><Icon size={18} className="text-blue-600" />{children}</h2>{action}</div>;

const DashboardSkeleton = () => <div className="space-y-6"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-5">{Array.from({ length: 5 }).map((_, i) => <div key={i} className="rounded-2xl border border-slate-200 bg-white p-5"><Skeleton className="mb-6 h-10 w-10 rounded-xl" /><Skeleton className="mb-3 h-3 w-24" /><Skeleton className="h-7 w-32" /></div>)}</div><div className="grid grid-cols-1 gap-6 xl:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-6 xl:col-span-2"><Skeleton className="mb-8 h-5 w-48" /><Skeleton className="h-[280px] w-full" /></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><Skeleton className="mb-8 h-5 w-44" /><Skeleton className="h-[280px] w-full" /></div></div><div className="grid grid-cols-1 gap-6 xl:grid-cols-2">{[1, 2].map(i => <div key={i} className="rounded-2xl border border-slate-200 bg-white p-6"><Skeleton className="mb-8 h-5 w-52" /><Skeleton className="h-[240px] w-full" /></div>)}</div></div>;

const Dashboard = () => {
  const [data, setData] = useState<DashboardData | null>(null);
  const [branches, setBranches] = useState<Branch[]>([]);
  const [selectedBranchId, setSelectedBranchId] = useState(localStorage.getItem('selectedBranchId') || '');
  const [revenueFilter, setRevenueFilter] = useState<'hour' | 'week' | 'month'>('hour');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [updatedAt, setUpdatedAt] = useState<Date | null>(null);
  const userRole = localStorage.getItem('userRole');
  const ownBranchId = localStorage.getItem('selectedBranchId');

  const fetchData = useCallback(async (signal?: AbortSignal) => {
    setLoading(true); setError(false);
    try {
      const query = selectedBranchId ? `?branchId=${encodeURIComponent(selectedBranchId)}` : '';
      const response = await fetch(`${API_URL}/api/Dashboard/summary${query}`, { signal });
      if (!response.ok) throw new Error('Dashboard request failed');
      setData(await response.json() as DashboardData); setUpdatedAt(new Date());
    } catch (requestError) { if ((requestError as Error).name !== 'AbortError') setError(true); }
    finally { if (!signal?.aborted) setLoading(false); }
  }, [selectedBranchId]);

  useEffect(() => { fetch(`${API_URL}/api/Branch`).then(response => response.ok ? response.json() : []).then(setBranches).catch(() => setBranches([])); }, []);
  useEffect(() => { const controller = new AbortController(); fetchData(controller.signal); return () => controller.abort(); }, [fetchData]);

  const activeChartData = useMemo(() => {
    if (!data) return [];
    if (revenueFilter === 'week') return data.weeklyRevenue.map(item => ({ time: item.date, amount: item.amount }));
    if (revenueFilter === 'month') return data.monthlyRevenue.map(item => ({ time: item.month, amount: item.amount }));
    return data.chartData;
  }, [data, revenueFilter]);
  const selectedBranchName = branches.find(branch => branch.id === selectedBranchId)?.name;
  const profit = data?.estimatedProfit || 0;
  const hasBranchData = (data?.branchRevenue?.length || 0) > 0;

  if (loading && !data) return <main className="min-h-screen bg-slate-50 p-4 sm:p-6 lg:p-8"><DashboardSkeleton /><div className="mt-4 flex items-center justify-center gap-2 text-xs font-semibold text-slate-400"><Loader2 size={14} className="animate-spin" />Đang tải dữ liệu...</div></main>;
  if (error && !data) return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-6"><div className="max-w-md rounded-2xl border border-red-100 bg-white p-8 text-center shadow-sm"><AlertCircle className="mx-auto mb-4 text-red-500" size={40} /><h1 className="text-lg font-bold text-slate-800">Không thể tải dữ liệu dashboard.</h1><p className="mt-2 text-sm text-slate-500">Vui lòng kiểm tra kết nối và thử lại.</p><button onClick={() => fetchData()} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white hover:bg-blue-700"><RefreshCw size={16} />Thử lại</button></div></main>;

  const kpis = [
    { label: 'Doanh thu', value: currency(data?.todayRevenue), note: `${(data?.revenueTrend || 0) >= 0 ? '↑' : '↓'} ${Math.abs(data?.revenueTrend || 0).toFixed(1)}% so với hôm qua`, icon: DollarSign, tone: 'blue' },
    { label: 'Đơn hàng', value: `${data?.totalOrders || 0}`, note: 'Đơn hoàn thành hôm nay', icon: ShoppingBag, tone: 'emerald' },
    { label: 'Khách hàng', value: `${data?.customerCount || 0}`, note: 'Khách hàng hôm nay', icon: Users, tone: 'amber' },
    { label: 'Chi phí', value: currency(data?.totalExpenses), note: 'Chi phí ghi nhận hôm nay', icon: CreditCard, tone: 'rose' },
    { label: 'Lợi nhuận ước tính', value: currency(profit), note: 'Theo CostPrice hiện tại', icon: TrendingUp, tone: 'violet' },
  ];
  const toneClasses: Record<string, string> = { blue: 'bg-blue-50 text-blue-600', emerald: 'bg-emerald-50 text-emerald-600', amber: 'bg-amber-50 text-amber-600', rose: 'bg-rose-50 text-rose-600', violet: 'bg-violet-50 text-violet-600' };

  return <main className="min-h-screen bg-slate-50 p-4 text-slate-800 sm:p-6 lg:p-8">
    <header className="mb-7 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-blue-600"><LayoutDashboard size={15} />Restaurant POS</div><h1 className="text-2xl font-extrabold tracking-tight text-slate-900 sm:text-3xl">Dashboard</h1><p className="mt-1 text-sm text-slate-500">Tổng quan hoạt động nhà hàng{selectedBranchName ? ` · ${selectedBranchName}` : ''}</p></div><div className="flex flex-col gap-2 sm:flex-row sm:items-center"><label className="relative flex items-center"><span className="sr-only">Chọn cơ sở</span><select value={selectedBranchId} onChange={event => { setSelectedBranchId(event.target.value); localStorage.setItem('selectedBranchId', event.target.value); }} disabled={userRole === 'manager'} className="w-full appearance-none rounded-xl border border-slate-200 bg-white py-2.5 pl-4 pr-10 text-sm font-semibold text-slate-700 shadow-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100 sm:w-auto">{userRole === 'admin' && <option value="">Tất cả cơ sở</option>}{branches.filter(b => userRole === 'admin' || b.id === ownBranchId).map(branch => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><ChevronDown size={16} className="pointer-events-none absolute right-3 text-slate-400" /></label><button aria-label="Làm mới dashboard" onClick={() => fetchData()} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-600 shadow-sm hover:bg-slate-50"><RefreshCw size={16} className={loading ? 'animate-spin' : ''} />Làm mới</button></div></header>
    {error && <div role="alert" className="mb-5 flex items-center justify-between rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700"><span className="flex items-center gap-2"><AlertCircle size={16} />Không thể tải dữ liệu dashboard mới nhất.</span><button onClick={() => fetchData()} className="font-bold underline">Thử lại</button></div>}
    <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-5">{kpis.map(({ label, value, note, icon: Icon, tone }) => <Card key={label}><div className="flex items-start justify-between"><div className={`rounded-xl p-2.5 ${toneClasses[tone]}`}><Icon size={19} /></div>{label === 'Lợi nhuận ước tính' && <span className="text-[10px] font-bold uppercase text-slate-400">Ước tính</span>}</div><p className="mt-5 text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 truncate text-xl font-extrabold text-slate-900">{value}</p><p className="mt-2 text-xs font-semibold text-slate-400">{note}</p></Card>)}</div>
    <div className="grid grid-cols-1 gap-6 xl:grid-cols-3"><Card className="xl:col-span-2"><SectionTitle icon={BarChart3} action={<div className="flex rounded-lg bg-slate-100 p-1">{([['hour', 'Hôm nay'], ['week', '7 ngày'], ['month', '12 tháng']] as const).map(([key, label]) => <button key={key} onClick={() => setRevenueFilter(key)} className={`rounded-md px-2.5 py-1.5 text-xs font-bold ${revenueFilter === key ? 'bg-white text-blue-600 shadow-sm' : 'text-slate-400 hover:text-slate-600'}`}>{label}</button>)}</div>}>Doanh thu theo thời gian</SectionTitle><div className="h-[280px]">{activeChartData.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={activeChartData}><defs><linearGradient id="dashboardRevenue" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#2563eb" stopOpacity={0.25} /><stop offset="95%" stopColor="#2563eb" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e2e8f0" strokeDasharray="3 3" /><XAxis dataKey="time" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#94a3b8' }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#94a3b8' }} tickFormatter={compactCurrency} /><Tooltip formatter={(value: number) => [currency(value), 'Doanh thu']} /><Area type="monotone" dataKey="amount" stroke="#2563eb" strokeWidth={3} fill="url(#dashboardRevenue)" /></AreaChart></ResponsiveContainer> : <EmptyState />}</div></Card><Card><SectionTitle icon={TrendingUp}>So sánh hiệu quả cơ sở</SectionTitle>{hasBranchData ? <div className="h-[280px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={data?.branchRevenue} layout="vertical" margin={{ left: 15, right: 20 }}><CartesianGrid horizontal={false} stroke="#e2e8f0" /><XAxis type="number" hide /><YAxis type="category" dataKey="name" width={85} axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#64748b' }} /><Tooltip formatter={(value: number) => [currency(value), 'Doanh thu']} /><Bar dataKey="value" radius={[0, 8, 8, 0]}>{data?.branchRevenue.map((_, index) => <Cell key={index} fill={COLORS[index % COLORS.length]} />)}</Bar></BarChart></ResponsiveContainer></div> : <EmptyState text="Chưa có dữ liệu so sánh cơ sở." />}</Card></div>
    <div className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-2"><Card><SectionTitle icon={BarChart3}>Doanh thu & Chi phí</SectionTitle><div className="h-[240px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{ name: 'Hôm nay', revenue: data?.todayRevenue || 0, expense: data?.totalExpenses || 0 }]}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="name" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} tickFormatter={compactCurrency} /><Tooltip formatter={(value: number, name: string) => [currency(value), name === 'revenue' ? 'Doanh thu' : 'Chi phí']} /><Legend formatter={value => value === 'revenue' ? 'Doanh thu' : 'Chi phí'} /><Bar dataKey="revenue" fill="#2563eb" radius={[6, 6, 0, 0]} /><Bar dataKey="expense" fill="#f97316" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div><div className={`mt-4 flex items-center justify-between rounded-xl px-4 py-3 ${profit >= 0 ? 'bg-emerald-50' : 'bg-rose-50'}`}><span className="text-sm font-bold text-slate-600">Lợi nhuận ước tính</span><span className={`text-lg font-extrabold ${profit >= 0 ? 'text-emerald-700' : 'text-rose-600'}`}>{currency(profit)}</span></div></Card><Card><SectionTitle icon={Package}>Top sản phẩm bán chạy</SectionTitle>{data?.topProducts?.length ? <div className="space-y-4">{data.topProducts.map((product, index) => { const max = data.topProducts[0]?.quantity || 1; return <div key={`${product.name}-${index}`}><div className="mb-1.5 flex items-center justify-between gap-3 text-sm"><span className="truncate font-semibold text-slate-700"><span className="mr-2 inline-flex h-6 w-6 items-center justify-center rounded-lg bg-slate-100 text-xs font-extrabold text-slate-500">{index + 1}</span>{product.name}</span><span className="shrink-0 font-bold text-slate-500">{product.quantity} lượt</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-500" style={{ width: `${Math.min(100, product.quantity / max * 100)}%` }} /></div></div> })}</div> : <EmptyState />}</Card></div>
    <div className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-2"><Card><SectionTitle icon={CheckCircle2}>Trạng thái đơn hàng</SectionTitle>{data?.orderStatuses?.length ? <div className="h-[240px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.orderStatuses} dataKey="value" nameKey="name" innerRadius={65} outerRadius={90} paddingAngle={4}>{data.orderStatuses.map((_, index) => <Cell key={index} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip /><Legend /></PieChart></ResponsiveContainer></div> : <EmptyState text="Backend chưa cung cấp thống kê trạng thái đơn hàng." />}</Card><Card><SectionTitle icon={CreditCard}>Phương thức thanh toán</SectionTitle>{data?.paymentMethods?.length ? <div className="h-[240px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.paymentMethods} dataKey="value" nameKey="name" innerRadius={65} outerRadius={90} paddingAngle={4}>{data.paymentMethods.map((_, index) => <Cell key={index} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip /><Legend /></PieChart></ResponsiveContainer></div> : <EmptyState text="Backend chưa cung cấp thống kê phương thức thanh toán." />}</Card></div>
    <Card className="mt-6 overflow-hidden p-0"><div className="p-5 pb-3"><SectionTitle icon={Clock3}>Đơn hàng gần đây</SectionTitle></div>{data?.recentOrders?.length ? <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-y border-slate-100 bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Mã đơn</th><th className="px-5 py-3">Cơ sở</th><th className="px-5 py-3">Bàn</th><th className="px-5 py-3">Tổng tiền</th><th className="px-5 py-3">Trạng thái</th><th className="px-5 py-3">Thời gian</th></tr></thead><tbody className="divide-y divide-slate-100">{data.recentOrders.map((order, index) => <tr key={`${order.invoiceCode}-${index}`} className="hover:bg-slate-50"><td className="px-5 py-4 font-bold text-blue-600">{order.invoiceCode || '—'}</td><td className="px-5 py-4 text-slate-500">{order.branchName || selectedBranchName || '—'}</td><td className="px-5 py-4 text-slate-500">{order.tableName || 'Mang về'}</td><td className="px-5 py-4 font-bold text-slate-800">{currency(order.totalAmount)}</td><td className="px-5 py-4">{order.status ? <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">{order.status}</span> : <span className="text-slate-400">Backend chưa cung cấp</span>}</td><td className="px-5 py-4 text-slate-500">{new Date(order.createdAt).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' })}</td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState /></div>}</Card>
    <Card className="mt-6"><SectionTitle icon={BarChart3}>Tổng quan hai cơ sở</SectionTitle>{hasBranchData ? <div className="grid grid-cols-1 gap-4 md:grid-cols-2">{data?.branchRevenue.map((branch, index) => <div key={branch.name} className="rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold text-slate-800">{branch.name}</h3><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: COLORS[index % COLORS.length] }} /></div><div className="grid grid-cols-2 gap-3"><div><p className="text-xs text-slate-400">Doanh thu</p><p className="mt-1 font-extrabold text-slate-800">{currency(branch.value)}</p></div><div><p className="text-xs text-slate-400">Đơn hàng</p><p className="mt-1 text-xs font-bold text-slate-500">Backend chưa cung cấp</p></div><div><p className="text-xs text-slate-400">Chi phí</p><p className="mt-1 text-xs font-bold text-slate-500">Backend chưa cung cấp</p></div><div><p className="text-xs text-slate-400">Lợi nhuận ước tính</p><p className="mt-1 text-xs font-bold text-slate-500">Backend chưa cung cấp</p></div></div></div>)}</div> : <EmptyState text="Chưa có dữ liệu theo cơ sở." />}</Card>
    <footer className="flex flex-col gap-2 py-5 text-xs text-slate-400 sm:flex-row sm:items-center sm:justify-between"><span>Lợi nhuận là số liệu ước tính dựa trên CostPrice, không phải COGS theo tồn kho thực tế.</span><span>{updatedAt ? `Cập nhật lúc ${updatedAt.toLocaleTimeString('vi-VN')}` : 'Chưa cập nhật'}{loading && data ? ' · Đang cập nhật...' : ''}</span></footer>
  </main>;
};

export default Dashboard;
